# Generated by Django 5.2.8 on 2025-11-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="chef_notes",
            field=models.TextField(blank=True, help_text="Private notes for the chef"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_public",
            field=models.BooleanField(default=True, help_text="Show on guest menu"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(
                blank=True, help_text="Public description for the menu"
            ),
        ),
    ]
