# Generated by Django 5.2.8 on 2025-11-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_recipe_chef_notes_recipe_is_public_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="in_stock",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="quantity",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Current stock quantity",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                help_text="Low stock alert threshold",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(
                choices=[
                    ("g", "Gram"),
                    ("kg", "Kilogram"),
                    ("ml", "Milliliter"),
                    ("l", "Liter"),
                    ("pc", "Piece"),
                ],
                default="g",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount required per serving",
                max_digits=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="quantity_display",
            field=models.CharField(
                blank=True, help_text="Display text e.g. '200g'", max_length=50
            ),
        ),
    ]
