# Generated by Django 5.2.8 on 2025-11-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_ingredient_in_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="note",
            field=models.CharField(
                blank=True, help_text="Customer special request", max_length=200
            ),
        ),
    ]
