# Generated by Django 5.2.8 on 2025-11-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_orderitem_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#10b981", help_text="Hex color code", max_length=7
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "summary",
                    models.TextField(blank=True, help_text="文章摘要", max_length=500),
                ),
                ("content", models.TextField(help_text="Markdown 格式内容")),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="blog/"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, help_text="是否发布"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, help_text="是否精选"),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="api.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
