# Generated by Django 6.0.1 on 2026-02-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ailabconversation_ailabmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ailabmessage',
            name='sub_turns',
            field=models.JSONField(blank=True, help_text='工具调用时间线 [{reasoning, toolCall}]', null=True),
        ),
    ]
