# Generated by Django 6.0.1 on 2026-02-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ailabmessage_sub_turns'),
    ]

    operations = [
        migrations.AddField(
            model_name='ailabmessage',
            name='model_name',
            field=models.CharField(blank=True, help_text='使用的模型名称', max_length=50, null=True),
        ),
    ]
