# Generated by Django 5.2.8 on 2026-04-13 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ailabmessage_model_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icon', models.CharField(default='📁', help_text='文件夹图标 emoji', max_length=10)),
                ('color', models.CharField(default='#6366f1', help_text='主题色', max_length=7)),
                ('description', models.TextField(blank=True, help_text='分类描述')),
                ('order', models.IntegerField(default=0, help_text='排序权重，数字越小越靠前')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='api.category'),
        ),
    ]
