# Generated by Django 5.2.8 on 2026-04-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_category_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='related_posts',
            field=models.ManyToManyField(blank=True, help_text='手动关联的文章（知识图谱）', to='api.blogpost'),
        ),
    ]
