# Generated by Django 5.2.8 on 2026-04-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_blogpost_related_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='ailabconversation',
            name='token_usage',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
