# Generated by Django 5.2.8 on 2026-04-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_ailabinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='ailabmessage',
            name='cache_tokens',
            field=models.PositiveIntegerField(default=0, help_text='该轮命中 / 写入 cache 的 tokens'),
        ),
        migrations.AddField(
            model_name='ailabmessage',
            name='completion_tokens',
            field=models.PositiveIntegerField(default=0, help_text='该轮 completion tokens'),
        ),
        migrations.AddField(
            model_name='ailabmessage',
            name='prompt_tokens',
            field=models.PositiveIntegerField(default=0, help_text='该轮计费 prompt tokens（包含 cache hit）'),
        ),
    ]
