# Generated by Django 5.2.8 on 2026-05-16 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_ailabmessage_file_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ailabmessage',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='ailabinvite',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ailabinvite',
            name='used_by',
        ),
        migrations.RemoveField(
            model_name='ailabnotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='AiLabConversation',
        ),
        migrations.DeleteModel(
            name='AiLabMessage',
        ),
        migrations.DeleteModel(
            name='AiLabInvite',
        ),
        migrations.DeleteModel(
            name='AiLabNotification',
        ),
    ]
