# Generated by Django 5.2.8 on 2026-02-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='groq_api_key',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
