# Generated by Django 5.2.8 on 2026-04-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_encrypt_existing_groq_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_lab_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_lab_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
