# Generated by Django 5.2.8 on 2026-05-16 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_ai_lab_activated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ai_lab_activated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ai_lab_enabled',
        ),
    ]
