# Generated by Django 4.2.27 on 2025-12-19 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("question", models.TextField()),
                ("spread_type", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ai_interpretation", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReadingCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_index", models.IntegerField()),
                ("position_name", models.CharField(max_length=100)),
                ("is_reversed", models.BooleanField(default=False)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.tarotcard",
                    ),
                ),
                (
                    "reading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="readings.reading",
                    ),
                ),
            ],
            options={
                "ordering": ["position_index"],
            },
        ),
    ]
