# Generated by Django 4.2.27 on 2025-12-20 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("readings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Spread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("name_cn", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("card_count", models.IntegerField()),
                ("positions", models.JSONField()),
                ("layout", models.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name="reading",
            name="spread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="readings.spread",
            ),
        ),
    ]
