# Generated by Django 4.2.27 on 2025-12-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(db_index=True, max_length=100)),
                ("question_text", models.TextField()),
                ("options", models.JSONField()),
                ("answer", models.CharField(max_length=500)),
                ("explanation", models.TextField()),
                ("seed_question", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
