name: MyWebInterpretation

options:
  createIntermediateGroups: true
  indentWidth: 2
  tabWidth: 2

configs:
  Debug: debug
  Release: release

configFiles:
  Debug: Configs/Debug.xcconfig
  Release: Configs/Release.xcconfig

settings:
  base:
    MARKETING_VERSION: 0.1.0
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Automatic

targets:
  MyWebInterpretationApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: MyWebInterpretationApp
        excludes:
          - Resources/Info-Debug.plist
          - Resources/Info-Release.plist
    settings:
      base:
        PRODUCT_NAME: Interpretation
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      testTargets: []
      storeKitConfiguration: Configuration.storekit
