# Generated by Django 6.0.1 on 2026-02-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
