# Generated by Django 6.0.1 on 2026-02-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_add_address_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=models.ImageField(blank=True, upload_to='receipts/%Y/%m/'),
        ),
    ]
