# Generated by Django on 2025-12-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_add_source_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="course_id",
            field=models.CharField(
                db_index=True, default="software-tools", max_length=100
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["course_id", "topic"], name="questions_course_topic_idx"),
        ),
    ]

