# Generated by Django on 2025-12-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_add_course_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                db_index=True,
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["course_id", "difficulty"], name="questions_course_diff_idx"),
        ),
    ]

