# Generated by Django 6.0.1 on 2026-01-28 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_add_difficulty'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='question',
            new_name='questions_q_course__950ef5_idx',
            old_name='questions_course_topic_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='questions_q_course__8e8391_idx',
            old_name='questions_course_diff_idx',
        ),
    ]
