# Generated by Django 5.2.8 on 2026-04-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_rename_questions_course_topic_idx_questions_q_course__950ef5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('fill', 'Fill in the Blank'), ('essay', 'Essay / Discussion')], db_index=True, default='mcq', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['course_id', 'question_type'], name='questions_q_course__b3644c_idx'),
        ),
    ]
