# Generated by Django 5.2.8 on 2026-04-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_question_type_alter_question_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source_chapter',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='source_excerpt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='KnowledgePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=100)),
                ('topic', models.CharField(db_index=True, max_length=100)),
                ('sequence', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=200)),
                ('definition', models.TextField()),
                ('details', models.JSONField(default=list)),
                ('importance', models.CharField(choices=[('core', 'Core'), ('supporting', 'Supporting')], default='core', max_length=16)),
                ('source_excerpt', models.TextField(blank=True, default='')),
                ('source_chapter', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['course_id', 'topic', 'sequence', 'id'],
                'indexes': [models.Index(fields=['course_id', 'topic'], name='questions_k_course__3dc495_idx'), models.Index(fields=['course_id', 'topic', 'sequence'], name='questions_k_course__33a2b9_idx')],
            },
        ),
    ]
