# Generated by Django 5.2.8 on 2026-04-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_question_source_chapter_question_source_excerpt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='generation_context',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
