# Generated by Django 5.2.8 on 2026-05-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_question_generation_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=100)),
                ('topic', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('messages', models.JSONField(default=list)),
                ('study_mode', models.CharField(default='study', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course_id', '-created_at'], name='questions_c_course__35d7af_idx')],
            },
        ),
    ]
