# Generated by Django 5.2.8 on 2026-05-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_chatnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatnote',
            name='key_points',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='chatnote',
            name='note_type',
            field=models.CharField(choices=[('archive', 'Chat Archive'), ('card', 'Knowledge Card')], default='archive', max_length=10),
        ),
        migrations.AddField(
            model_name='chatnote',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatnote',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
