# Generated by Django 5.2.8 on 2026-05-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_chatnote_key_points_chatnote_note_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepoint',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
