# Generated by Django 4.2.27 on 2025-12-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TarotCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("number", models.IntegerField()),
                (
                    "arcana",
                    models.CharField(
                        choices=[("Major", "Major"), ("Minor", "Minor")], max_length=10
                    ),
                ),
                (
                    "suit",
                    models.CharField(
                        choices=[
                            ("Wands", "Wands"),
                            ("Cups", "Cups"),
                            ("Swords", "Swords"),
                            ("Pentacles", "Pentacles"),
                            ("None", "None"),
                        ],
                        default="None",
                        max_length=10,
                    ),
                ),
                ("img", models.CharField(max_length=100)),
                ("fortune_telling", models.JSONField(default=list)),
                ("keywords", models.JSONField(default=list)),
                ("meanings_light", models.JSONField(default=list)),
                ("meanings_shadow", models.JSONField(default=list)),
            ],
        ),
    ]
